/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista.logs;

/**
 *
 * @author Steven Medrano
 */
public class Logs_Vista extends javax.swing.JPanel {

    /**
     * Creates new form Logs_Vista
     */
    public Logs_Vista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        panelPrincipal = new javax.swing.JPanel();
        btnInicio = new javax.swing.JButton();
        btnAplicarFiltro = new javax.swing.JButton();
        btnExcel = new javax.swing.JButton();
        txtDe = new javax.swing.JTextField();
        txtHasta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnRetirarFiltro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaUsers = new javax.swing.JTable();

        panelPrincipal.setLayout(new java.awt.GridBagLayout());

        btnInicio.setBackground(new java.awt.Color(181, 255, 0));
        btnInicio.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(53, 6, 0, 0);
        panelPrincipal.add(btnInicio, gridBagConstraints);

        btnAplicarFiltro.setBackground(new java.awt.Color(153, 204, 255));
        btnAplicarFiltro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAplicarFiltro.setText("Aplicar Filtro");
        btnAplicarFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplicarFiltroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 50;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(77, 18, 0, 14);
        panelPrincipal.add(btnAplicarFiltro, gridBagConstraints);

        btnExcel.setBackground(new java.awt.Color(181, 255, 0));
        btnExcel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnExcel.setText("Excel");
        btnExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 115;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(68, 18, 0, 14);
        panelPrincipal.add(btnExcel, gridBagConstraints);

        txtDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDeActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 77;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 6, 0, 14);
        panelPrincipal.add(txtDe, gridBagConstraints);

        txtHasta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHastaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 77;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(64, 6, 0, 14);
        panelPrincipal.add(txtHasta, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("De:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(60, 18, 0, 0);
        panelPrincipal.add(jLabel1, gridBagConstraints);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Hasta:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(64, 18, 0, 0);
        panelPrincipal.add(jLabel2, gridBagConstraints);

        btnRetirarFiltro.setBackground(new java.awt.Color(243, 160, 26));
        btnRetirarFiltro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRetirarFiltro.setText("Retirar Filtro");
        btnRetirarFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRetirarFiltroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.ipadx = 52;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(61, 18, 0, 14);
        panelPrincipal.add(btnRetirarFiltro, gridBagConstraints);

        tablaUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "id", "Concepto", "Codigo", "id"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaUsers);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 9;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 549;
        gridBagConstraints.ipady = 482;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 19, 0);
        panelPrincipal.add(jScrollPane1, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        // TODO add your handling code here:
         // Logic for btnInicioActionPerformed
        System.out.println("Inicio button clicked");
        // You can add more functionality as needed, e.g., navigating to the main view
    }//GEN-LAST:event_btnInicioActionPerformed

    private void txtHastaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHastaActionPerformed
        // TODO add your handling code here:
        // Logic for txtHastaActionPerformed
        System.out.println("Hasta text field action performed");
        // You can add more functionality as needed, e.g., validating input
    }//GEN-LAST:event_txtHastaActionPerformed

    private void txtDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDeActionPerformed
        // TODO add your handling code here:
        // Logic for txtDeActionPerformed
        System.out.println("De text field action performed");
        // You can add more functionality as needed, e.g., validating input
    }//GEN-LAST:event_txtDeActionPerformed

    private void btnRetirarFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRetirarFiltroActionPerformed
        // TODO add your handling code here:
         // Logic for btnRetirarFiltroActionPerformed
        System.out.println("Retirar Filtro button clicked");
        // Remove filters from the table
        DefaultTableModel model = (DefaultTableModel) tablaUsers.getModel();
        // Assume originalData is a List of your original table data
        model.setRowCount(0); // Clear the table
        for (Object[] row : originalData) {
            model.addRow(row);
        }
    }//GEN-LAST:event_btnRetirarFiltroActionPerformed

    private void btnAplicarFiltroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplicarFiltroActionPerformed
        // TODO add your handling code here:
         // Logic for btnAplicarFiltroActionPerformed
        System.out.println("Aplicar Filtro button clicked");
        // Apply filters to the table
        DefaultTableModel model = (DefaultTableModel) tablaUsers.getModel();
        model.setRowCount(0); // Clear the table
        String de = txtDe.getText();
        String hasta = txtHasta.getText();
        // Apply your filter logic here and add the filtered rows back to the model
        for (Object[] row : originalData) {
            if (/* your filter condition based on de and hasta */) {
                model.addRow(row);
            }
        }
    }//GEN-LAST:event_btnAplicarFiltroActionPerformed

    private void btnExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcelActionPerformed
        // TODO add your handling code here:
          // Logic for btnExcelActionPerformed
        System.out.println("Excel button clicked");
        // Export the table data to an Excel file
        try {
            // Implement your logic to export data to Excel
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnExcelActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplicarFiltro;
    private javax.swing.JButton btnExcel;
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnRetirarFiltro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelPrincipal;
    private javax.swing.JTable tablaUsers;
    private javax.swing.JTextField txtDe;
    private javax.swing.JTextField txtHasta;
    // End of variables declaration//GEN-END:variables
}
