/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.Inicio;

import java.awt.Color;
import modelos.users;

import vistas.documentos.DocumentosVista;
import vistas.libro_mayor.LibroMayorVista;
import vistas.libro_diario.LibroDiarioVista;
import vistas.documentos.DocumentosVista;
import vista.user.VistaUsers;
import vistas.cuentas.cuentasVista;

/**
 *
 * @author jajon
 */
public class Inicio extends javax.swing.JFrame {

    users user;
    /**
     * Creates new form Inicio
     */
    public Inicio(){
        initComponents();
    }
    
    public Inicio(users user) {
        this.user = user;
        initComponents();
        
        String rol = user.getUser_rol();
        
        lblUser.setText(user.getUser_name());
        
        if(rol.equals("Gerente")){
            btnlogs.disable();
            //btncuentas.setBackground(Color.gray);
            btnlogs.setVisible(false);
            
            btnusers.setVisible(false);
            btnusers.disable();
            
            btndocus.disable();
            btndocus.setVisible(false);
        }
        
        if(rol.equals("Administrador")){
            btnlogs.disable();
            //btncuentas.setBackground(Color.gray);
            btnlogs.setVisible(false);
            
            btnusers.setVisible(false);
            btnusers.disable();
        }
        
        if(rol.equals("Contador y Auxiliar")){
            btnlogs.disable();
            //btncuentas.setBackground(Color.gray);
            btnlogs.setVisible(false);
            
            btnusers.setVisible(false);
            btnusers.disable();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Panel_Inicio = new javax.swing.JPanel();
        btnCerrar2 = new javax.swing.JButton();
        btnlibroM = new javax.swing.JButton();
        lblUser = new javax.swing.JLabel();
        btncuentas = new javax.swing.JButton();
        btnlibroD = new javax.swing.JButton();
        btndocus = new javax.swing.JButton();
        btnlogs = new javax.swing.JButton();
        btnusers = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        btnCerrar2.setBackground(new java.awt.Color(255, 51, 51));
        btnCerrar2.setFont(new java.awt.Font("Meiryo UI", 1, 18)); // NOI18N
        btnCerrar2.setForeground(new java.awt.Color(255, 255, 255));
        btnCerrar2.setText("Cerrar");
        btnCerrar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrar2ActionPerformed(evt);
            }
        });

        btnlibroM.setBackground(new java.awt.Color(51, 204, 0));
        btnlibroM.setFont(new java.awt.Font("Meiryo UI", 1, 18)); // NOI18N
        btnlibroM.setForeground(new java.awt.Color(255, 255, 255));
        btnlibroM.setText("Libro Mayor");
        btnlibroM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlibroMActionPerformed(evt);
            }
        });

        lblUser.setBackground(new java.awt.Color(0, 0, 0));
        lblUser.setFont(new java.awt.Font("Meiryo UI", 1, 18)); // NOI18N
        lblUser.setText("User");

        btncuentas.setBackground(new java.awt.Color(255, 51, 51));
        btncuentas.setFont(new java.awt.Font("Meiryo UI", 1, 18)); // NOI18N
        btncuentas.setForeground(new java.awt.Color(255, 255, 255));
        btncuentas.setText("Cuentas");
        btncuentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncuentasActionPerformed(evt);
            }
        });

        btnlibroD.setBackground(new java.awt.Color(154, 217, 234));
        btnlibroD.setFont(new java.awt.Font("Meiryo UI", 1, 18)); // NOI18N
        btnlibroD.setText("Libro Diario");
        btnlibroD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlibroDActionPerformed(evt);
            }
        });

        btndocus.setBackground(new java.awt.Color(51, 153, 255));
        btndocus.setFont(new java.awt.Font("Meiryo UI", 1, 18)); // NOI18N
        btndocus.setForeground(new java.awt.Color(255, 255, 255));
        btndocus.setText("Documentos");
        btndocus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndocusActionPerformed(evt);
            }
        });

        btnlogs.setBackground(new java.awt.Color(204, 204, 0));
        btnlogs.setFont(new java.awt.Font("Meiryo UI", 1, 18)); // NOI18N
        btnlogs.setForeground(new java.awt.Color(255, 255, 255));
        btnlogs.setText("Logs");

        btnusers.setBackground(new java.awt.Color(102, 102, 255));
        btnusers.setFont(new java.awt.Font("Meiryo UI", 1, 18)); // NOI18N
        btnusers.setForeground(new java.awt.Color(255, 255, 255));
        btnusers.setText("Users");
        btnusers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnusersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Panel_InicioLayout = new javax.swing.GroupLayout(Panel_Inicio);
        Panel_Inicio.setLayout(Panel_InicioLayout);
        Panel_InicioLayout.setHorizontalGroup(
            Panel_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Panel_InicioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(Panel_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Panel_InicioLayout.createSequentialGroup()
                        .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addComponent(btnCerrar2, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Panel_InicioLayout.createSequentialGroup()
                        .addGroup(Panel_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnlibroD, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnlogs, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnusers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Panel_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btncuentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnlibroM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btndocus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))))
                .addGap(19, 19, 19))
        );
        Panel_InicioLayout.setVerticalGroup(
            Panel_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_InicioLayout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(Panel_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCerrar2)
                    .addComponent(lblUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(Panel_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlibroD, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnlibroM, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(Panel_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlogs, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncuentas, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(Panel_InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnusers, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btndocus, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Panel_Inicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndocusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndocusActionPerformed
        DocumentosVista docv = new DocumentosVista(this.user);
        docv.show();
        this.dispose();
    }//GEN-LAST:event_btndocusActionPerformed

    private void btnCerrar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrar2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrar2ActionPerformed

    private void btnlibroMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlibroMActionPerformed
        LibroMayorVista sisi = new LibroMayorVista(this.user);
        sisi.show();
        this.dispose();
    }//GEN-LAST:event_btnlibroMActionPerformed

    private void btnlibroDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlibroDActionPerformed
        LibroDiarioVista lidd = new LibroDiarioVista(this.user);
        lidd.show();
        this.dispose();
    }//GEN-LAST:event_btnlibroDActionPerformed

    private void btnusersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnusersActionPerformed
        VistaUsers usss = new VistaUsers();
        usss.show();
        this.dispose();
    }//GEN-LAST:event_btnusersActionPerformed

    private void btncuentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncuentasActionPerformed
        cuentasVista cnV = new cuentasVista(this.user);
        cnV.show();
        this.dispose();
    }//GEN-LAST:event_btncuentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_Inicio;
    private javax.swing.JButton btnCerrar2;
    private javax.swing.JButton btncuentas;
    private javax.swing.JButton btndocus;
    private javax.swing.JButton btnlibroD;
    private javax.swing.JButton btnlibroM;
    private javax.swing.JButton btnlogs;
    private javax.swing.JButton btnusers;
    private javax.swing.JLabel lblUser;
    // End of variables declaration//GEN-END:variables
}
