/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.libro_diario;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
//import Utilidades_configuracion.CustomCellLabelTable;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;

import modelos.cuentas;
import modelos.documentos;
import modelos.users;
import modelos.logs;
import modelos.libro_diario;

import vistas.Inicio.Inicio;

/**
 *
 * @author Usuario
 */
public class LibroDiarioCrear extends javax.swing.JFrame {
    
    public ArrayList<cuentas> listaCuentas;
    public ArrayList<documentos> listaDocumentos;
    public ArrayList<users> listaUsers;
    public ArrayList<logs> listaLogs;
    
    users user1;
    /*
    public cuentas cuenta;
    public documentos doc;
    
    public logs log;
    /**
     * Creates new form LibroDiarioCrear
     */
    public LibroDiarioCrear(){
        initComponents();
    }
    
    public LibroDiarioCrear(users us) {
        this.user1 = us;
        initComponents();
        
        cuentas cuenta = new cuentas();
        documentos doc = new documentos();
        logs log = new logs();
        users user = new users();
        
        
        listaCuentas = cuenta.getCuentas();
        listaDocumentos = doc.getDocumentos();
        listaUsers = user.getUsers();
        listaLogs = log.getLogs();
        
        for(cuentas item : listaCuentas){
            this.cuenta1cmb.addItem(String.valueOf(item.getId_cuenta()));
            this.cuenta2cmb.addItem(String.valueOf(item.getId_cuenta()));
        }
        
        for(users item : listaUsers){
            this.idusercmb.addItem(String.valueOf(item.getId_user()));
        }
        
        for(documentos item : listaDocumentos){
            this.coddoccmb.addItem(String.valueOf(item.getId_documento()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnInicio = new javax.swing.JButton();
        btningresar = new javax.swing.JButton();
        cuenta1cmb = new javax.swing.JComboBox<>();
        lblDesdeMes = new javax.swing.JLabel();
        lblDesdeMes2 = new javax.swing.JLabel();
        txtvalor = new javax.swing.JTextField();
        coddoccmb = new javax.swing.JComboBox<>();
        lblDesdeMes3 = new javax.swing.JLabel();
        lblDesdeMes4 = new javax.swing.JLabel();
        txtfecha = new javax.swing.JFormattedTextField();
        btnagregardoc = new javax.swing.JButton();
        comunicar = new javax.swing.JLabel();
        idusercmb = new javax.swing.JComboBox<>();
        lblDesdeMes5 = new javax.swing.JLabel();
        cuenta2cmb = new javax.swing.JComboBox<>();
        lblDesdeMes1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnInicio.setBackground(new java.awt.Color(181, 229, 29));
        btnInicio.setFont(new java.awt.Font("Meiryo UI", 1, 18)); // NOI18N
        btnInicio.setText("Inicio");
        btnInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInicioActionPerformed(evt);
            }
        });

        btningresar.setBackground(new java.awt.Color(0, 204, 204));
        btningresar.setFont(new java.awt.Font("Meiryo UI", 1, 18)); // NOI18N
        btningresar.setText("Ingresar");
        btningresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btningresarActionPerformed(evt);
            }
        });

        cuenta1cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuenta1cmbActionPerformed(evt);
            }
        });

        lblDesdeMes.setBackground(new java.awt.Color(0, 0, 0));
        lblDesdeMes.setFont(new java.awt.Font("Meiryo UI", 1, 14)); // NOI18N
        lblDesdeMes.setText("cuenta a retirar");

        lblDesdeMes2.setBackground(new java.awt.Color(0, 0, 0));
        lblDesdeMes2.setFont(new java.awt.Font("Meiryo UI", 1, 14)); // NOI18N
        lblDesdeMes2.setText("Monto a efectuar($)");

        lblDesdeMes3.setBackground(new java.awt.Color(0, 0, 0));
        lblDesdeMes3.setFont(new java.awt.Font("Meiryo UI", 1, 14)); // NOI18N
        lblDesdeMes3.setText("Cod Documento");

        lblDesdeMes4.setBackground(new java.awt.Color(0, 0, 0));
        lblDesdeMes4.setFont(new java.awt.Font("Meiryo UI", 1, 14)); // NOI18N
        lblDesdeMes4.setText("Fecha");

        txtfecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));

        btnagregardoc.setBackground(new java.awt.Color(255, 102, 51));
        btnagregardoc.setFont(new java.awt.Font("Meiryo UI", 1, 18)); // NOI18N
        btnagregardoc.setForeground(new java.awt.Color(255, 255, 255));
        btnagregardoc.setText("Agregar Doc");

        comunicar.setBackground(new java.awt.Color(0, 0, 0));
        comunicar.setFont(new java.awt.Font("Meiryo UI", 1, 14)); // NOI18N
        comunicar.setText("###");

        idusercmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idusercmbActionPerformed(evt);
            }
        });

        lblDesdeMes5.setBackground(new java.awt.Color(0, 0, 0));
        lblDesdeMes5.setFont(new java.awt.Font("Meiryo UI", 1, 14)); // NOI18N
        lblDesdeMes5.setText("id user");

        cuenta2cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuenta2cmbActionPerformed(evt);
            }
        });

        lblDesdeMes1.setBackground(new java.awt.Color(0, 0, 0));
        lblDesdeMes1.setFont(new java.awt.Font("Meiryo UI", 1, 14)); // NOI18N
        lblDesdeMes1.setText("cuenta a abonar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDesdeMes2)
                            .addComponent(lblDesdeMes3)
                            .addComponent(lblDesdeMes4)
                            .addComponent(lblDesdeMes5))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(idusercmb, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(btningresar, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                                    .addComponent(txtvalor, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(coddoccmb, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtfecha))
                                .addGap(75, 75, 75)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comunicar)
                                    .addComponent(btnagregardoc, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDesdeMes1)
                                .addGap(34, 34, 34)
                                .addComponent(cuenta2cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblDesdeMes)
                                .addGap(34, 34, 34)
                                .addComponent(cuenta1cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(141, 141, 141)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idusercmb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDesdeMes5))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDesdeMes)
                        .addGap(14, 14, 14))
                    .addComponent(cuenta1cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDesdeMes1)
                    .addComponent(cuenta2cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDesdeMes2)
                    .addComponent(txtvalor, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btnagregardoc, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(55, 55, 55))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblDesdeMes3)
                                .addComponent(coddoccmb, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(79, 79, 79)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDesdeMes4)
                            .addComponent(txtfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comunicar)
                    .addComponent(btningresar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cuenta1cmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuenta1cmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuenta1cmbActionPerformed

    private void idusercmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idusercmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idusercmbActionPerformed

    private void btnInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInicioActionPerformed
        Inicio ini = new Inicio(this.user1);
        ini.show();
        this.dispose();
    }//GEN-LAST:event_btnInicioActionPerformed

    private void btningresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btningresarActionPerformed
        libro_diario libroDiario1 = new libro_diario();
        libro_diario libroDiario2 = new libro_diario();
        cuentas cuenta1 = new cuentas();
        cuentas cuenta2 = new cuentas();
        listaCuentas = cuenta1.getCuentas();
        
        double valor;
        
        //activo = pasivo + patrimonio
        //pasivo = activo - patrimonio
        //patrimonio = activo - pasivo
        
        cuenta1.setId_cuenta(Integer.parseInt(String.valueOf(cuenta1cmb.getSelectedItem())));
        cuenta2.setId_cuenta(Integer.parseInt(String.valueOf(cuenta2cmb.getSelectedItem())));
        
        for(cuentas item : listaCuentas){
            if(cuenta1.getId_cuenta() == item.getId_cuenta()){
                cuenta1.setNombre_cuenta(item.getNombre_cuenta());
                cuenta1.setTipo_cuenta(item.getTipo_cuenta());
            }
            if(cuenta2.getId_cuenta() == item.getId_cuenta()){
                cuenta2.setNombre_cuenta(item.getNombre_cuenta());
                cuenta2.setTipo_cuenta(item.getTipo_cuenta());
            }
        }
        
        valor = Double.parseDouble(txtvalor.getText());
        System.out.println(valor);
        
        libroDiario1.setId_cuenta(Integer.parseInt(String.valueOf(cuenta1cmb.getSelectedItem())));
        libroDiario1.setId_user(Integer.parseInt(String.valueOf(idusercmb.getSelectedItem())));
        libroDiario1.setFecha(txtfecha.getText());
        libroDiario1.setId_documento(Integer.parseInt(String.valueOf(coddoccmb.getSelectedItem())));
        
        libroDiario2.setId_cuenta(Integer.parseInt(String.valueOf(cuenta2cmb.getSelectedItem())));
        libroDiario2.setId_user(Integer.parseInt(String.valueOf(idusercmb.getSelectedItem())));
        libroDiario2.setFecha(txtfecha.getText());
        libroDiario2.setId_documento(Integer.parseInt(String.valueOf(coddoccmb.getSelectedItem())));
        
        //--------- EDITAR CON CUIDADO, ES IMPORTANTE SABER COMO ACTUALIZARAS LA BD EN SU CONJUNTO
        
        for(cuentas itm : listaCuentas){
            if(libroDiario1.getId_cuenta() == itm.getId_cuenta()){
                String tipo = itm.getTipo_cuenta();
                
                if(tipo.equals("activo") || tipo.equals("patrimonio")){
                    System.out.println("aqui");
                    libroDiario1.setDebe(valor);
                    double db = (valor - cuenta1.getSaldo());
                    cuenta1.setSaldo(db);
                    libroDiario1.setBalance(cuenta1.getSaldo());
                    cuenta1.setTipo_cuenta(itm.getTipo_cuenta());
                    cuenta1.setNombre_cuenta(itm.getNombre_cuenta());
                }
                if(tipo.equals("pasivo") || tipo.equals("gastos") || tipo.equals("ingresos")){
                    libroDiario1.setHaber(valor);
                    double hb = (valor - cuenta1.getSaldo());
                    cuenta1.setSaldo(hb);
                    libroDiario1.setBalance(cuenta1.getSaldo());
                    cuenta1.setTipo_cuenta(itm.getTipo_cuenta());
                    cuenta1.setNombre_cuenta(itm.getNombre_cuenta());
                }
            }
        }
        
        for(cuentas itm : listaCuentas){
            if(libroDiario2.getId_cuenta() == itm.getId_cuenta()){
                String tipo = itm.getTipo_cuenta();
                if(tipo.equals("activo") || tipo.equals("patrimonio")){
                    libroDiario2.setDebe(valor);
                    double db = (valor - cuenta2.getSaldo());
                    cuenta2.setSaldo(db);
                    libroDiario2.setBalance(cuenta2.getSaldo());
                    //cuenta2.setTipo_cuenta(itm.getTipo_cuenta());
                    //cuenta2.setNombre_cuenta(itm.getNombre_cuenta());
                    libroDiario2.setBalance(cuenta1.getSaldo());
                }
                if(tipo.equals("pasivo") || tipo.equals("gastos") || tipo.equals("ingresos")){
                    libroDiario2.setHaber(valor);
                    double hb = (valor - cuenta2.getSaldo());
                    
                    cuenta2.setSaldo(hb);
                    libroDiario2.setBalance(cuenta2.getSaldo());
                    //cuenta2.setTipo_cuenta(itm.getTipo_cuenta());
                    //cuenta2.setNombre_cuenta(itm.getNombre_cuenta());
                    libroDiario1.setBalance(cuenta2.getSaldo());
                }
            }
        }
        
        if(libroDiario1.insertLibroD(libroDiario1)>0){
            System.out.println("Se ha agregado el registro 1.");
        }else{
            System.out.println("No se agrego.");
        }
        
        if(libroDiario1.insertLibroD(libroDiario2)>0){
            System.out.println("Se ha agregado el registro 2.");
        }else{
            System.out.println("No se agrego.");
        }
        
        //////
        
        if(cuenta1.editCuenta(cuenta1)>0){
           System.out.println("Se ha actualizado la cuenta 1 saldo");
        }else{
            System.out.println("No se actualizo.");
        }
        
        if(cuenta2.editCuenta(cuenta2)>0){
           System.out.println("Se ha actualizado la cuenta 2 saldo");
        }else{
            System.out.println("No se actualizo.");
        }
    }//GEN-LAST:event_btningresarActionPerformed

    private void cuenta2cmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuenta2cmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cuenta2cmbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LibroDiarioCrear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LibroDiarioCrear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LibroDiarioCrear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LibroDiarioCrear.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LibroDiarioCrear().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInicio;
    private javax.swing.JButton btnagregardoc;
    private javax.swing.JButton btningresar;
    private javax.swing.JComboBox<String> coddoccmb;
    private javax.swing.JLabel comunicar;
    private javax.swing.JComboBox<String> cuenta1cmb;
    private javax.swing.JComboBox<String> cuenta2cmb;
    private javax.swing.JComboBox<String> idusercmb;
    private javax.swing.JLabel lblDesdeMes;
    private javax.swing.JLabel lblDesdeMes1;
    private javax.swing.JLabel lblDesdeMes2;
    private javax.swing.JLabel lblDesdeMes3;
    private javax.swing.JLabel lblDesdeMes4;
    private javax.swing.JLabel lblDesdeMes5;
    private javax.swing.JFormattedTextField txtfecha;
    private javax.swing.JTextField txtvalor;
    // End of variables declaration//GEN-END:variables
}
